# Stage 1: Build a production-grade ngnix lightweight container 
FROM nginx:alpine 


COPY index.html /usr/share/ngnix/html/ 
# Expose nginx standard web port 
EXPOSE 80 

CMD ["nginx", "-g", "daemon off"]